# Provision a webserver

# Largely inspired from https://www.digitalocean.com/community/tutorials/how-to-configure-apache-using-ansible-on-ubuntu-14-04

- hosts: all
  gather_facts: False
  become: true
# Because ubuntu 16 doesn't ship with python 2, a prerequiste for ansible
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: apache
  vars:
    document_root: /var/www/controlthepastcontrolthefuture
    domain: controlthepastcontrolthefuture.co.uk
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest

  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
        - restart apache2

  - name: create virtual host file
    template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

  - name: a2ensite {{ domain }}
    command: a2ensite {{ domain }}
    args:
      creates: /etc/apache2/sites-enabled/{{ domain }}.conf
    notify:
      - restart apache2

# TODO what are the best permissions here
  #- name: Create document root directory
  #  file: path={{ document_root }} state=directory
  #- name: Set sensible permissions
  #  file: path={{ document_root }} owner=www-data group=www-data mode=0644
  - command: sudo chown -R www-data:www-data {{ document_root }}

  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted

# TODO clone repository
#  - name: clone basic html template
#    git: repo=https://github.com/do-community/ansible-apache-tutorial.git dest=/var/www/example.com update=no
